### ISSUE TITLE
Error when creating a new project: ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by BlueFrog130** [managed-components/create-managed-component#4]
Tried to initialize a new managed component using

```
npm init managed-component
```

```
OS: Windows 10
Node: v18.1.0
npm: 8.11.0
create-managed-component: 1.0.10
```

Full error and input:

```
√ Display name: ... test-mc
√ Description: ... just a test
√ Path to svg icon: ... assets/icon.svg
√ Requested Permissions: »
√ Confirm new managed component?: {
  "displayName": "test-mc",
  "description": "just a test",
  "icon": "assets/icon.svg",
  "permissions": {}
} ... yes
node:internal/errors:466
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.mkdirSync (node:fs:1350:10)
    at exports.default (C:\Users\adamg\AppData\Local\npm-cache\_npx\b98a785dcc98b45a\node_modules\create-managed-component\dist\renderTemplate.js:13:22)
    at C:\Users\adamg\AppData\Local\npm-cache\_npx\b98a785dcc98b45a\node_modules\create-managed-component\dist\index.js:222:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by BlueFrog130** [comment]
Resolved by bc115d5b55bb23f6577936c8cfe3b490933f3ed8
